"""empty message

Revision ID: f5a09ff98805
Revises: 
Create Date: 2024-04-21 16:06:13.568278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a09ff98805'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_specie_id'), 'specie', ['id'], unique=False)
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('specieId', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('HEALTHY', 'CECITY', 'BURN', 'FROZEN', 'POISON', 'CONFUSION', name='charactersstatus'), nullable=True),
    sa.Column('reputation', sa.Integer(), nullable=False),
    sa.Column('bounty', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('gender', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['specieId'], ['specie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_bounty'), 'characters', ['bounty'], unique=False)
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_bounty'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_specie_id'), table_name='specie')
    op.drop_table('specie')
    # ### end Alembic commands ###
